spring:
  application:
    name: vpn-manager
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:/db/h2-db
    username: sa
    password: ""
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8081

security:
  user:
    username: user
    password: user

remote-server:
  url: 212.132.111.204
  username: root
  password: iLLPmky7

logging:
  level:
    org:
      springframework: INFO

retry:
  app:
    multiplier: 3
    backOffDelay: 1000
    maxAttempts: 5
